### ISSUE TITLE
More Overview Stats 2.1 Minor Issue

### ISSUE THREAD

**Issue by adamhl8** [Shirajuki/anki-redesign#16]
First of all, thank you for this addon. It's by far the best redesign/reskin of Anki available.

I'm having a very minor issue when using this in conjunction with [More Overview Stats 2.1](https://ankiweb.net/shared/info/738807903). The first line's formatting is a bit messed up:

![image](https://user-images.githubusercontent.com/1844269/161433919-d3060feb-cf77-4cef-a99a-c3197efbba39.png)

**Comment by Shirajuki** [comment]
Heyohello! I am very happy to know that you like the addon :D
Thank you for writing an issue, helping me further improve the addon for you and other users as well!
As for this same addon, I believe that I have written a fix for it already. It is my fault that it is not made clear yet in the changelogs. 😅 The fix can be toggled by setting the "addon_more_overview_stats" field to "true" in the config files, just as below:
```json
"addon_more_overview_stats": "true",
```

Sorry for a late answer, I have been taking a break from developing this addon due to studies. I'll be having easter break next week which means that there'll be updates coming soon! I hope you'll wait for this future update as well!
I'll keep this issue open in case the fix did not work for you. :) Feel free to continue this thread if so :D

**Comment by adamhl8** [comment]
That fixed it, thanks!
