### ISSUE TITLE
Night mode - Issue

### ISSUE THREAD

**Issue by bu1ur1in** [Shirajuki/anki-redesign#2]
There is an issue with the dark mode. Apparently some part appearing white.
![image](https://user-images.githubusercontent.com/97780469/149613680-980f28c0-a225-4cf7-812b-fde856ab88ed.png)

**Comment by Shirajuki** [comment]
Hello!
Thanks for writing an issue. As of now, I have only manually tested anki-redesign on 2.1.49 and thus the addon is quite untested.
Would you mind telling me your Anki version and enabled addons? I will look into it, and hopefully get this fixed asap. :D

**Comment by bu1ur1in** [comment]
Sure!
The Anki version is 2.1.49 and I'm attaching SS of the enabled addons if thats ok

![image](https://user-images.githubusercontent.com/97780469/149651600-ff131c06-bdcb-41e0-a6a8-f00f9c035ec4.png)

**Comment by Shirajuki** [comment]
Hello!
Thank you for your patience, I have not got this issue fixed :D. It was actually a problem on my fault as I didn't get to test the addon thoroughly on Mac computers. I had goofed up the CSS selectors a bit there. The fix for this issue will be featured on the next addon release/update :) Thank you very much for writing an issue and helping with the development of the addon! :D

**Comment by Shirajuki** [comment]
The new update is out 😊. Thank you for the wait! 🥳
