### ISSUE TITLE
"Full screen" plugin incompatibility

### ISSUE THREAD

**Issue by chezfo** [Shirajuki/anki-redesign#28]
"Full Screen" plugin
(1049863218)

In the version found on github https://github.com/mobedoor/No-Distractions-Full-Screen

The author of the plugin wrote: "05/31/2022: As long as this add-on version doesn't work on the newest Anki versions, use this fork: https://github.com/mobedoor/No-Distractions-Full-Screen"

Download link
https://github.com/mobedoor/No-Distractions-Full-Screen/releases/download/v4.1.8/NDFS.ankiaddon

**Comment by Shirajuki** [comment]
Hello hello, seems like a great add-on!
I'll try my best to incorporate an add-on compatibility fix for this on the next update of Anki-redesign.
Hope you'll wait till then! Thank you for being a user of Anki-redesign! :D

**Comment by chezfo** [comment]
I try to push that the desktop anki will use your appearance by default

**Comment by Shirajuki** [comment]
Hello! A new update of Anki-redesign was recently pushed out, adding a compatibility fix to NDFS! :D
The fix is not 100% compatible yet, so feel free to add more issues referring to the problems and potential issues you meet if that ever happens. Thank you for the request as well as being a user of Anki-redesign!
