### ISSUE TITLE
review buttons revert to default after the latest update + an error message

### ISSUE THREAD

**Issue by drunkzurg** [Shirajuki/anki-redesign#37]
![image](https://user-images.githubusercontent.com/89298319/181138366-bbebd4e9-4811-423b-8c5f-6e02744bd3df.png)

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-27 06:15:44

Caught exception:
Traceback (most recent call last):
  File "aqt.addons", line 256, in onAddonsDialog
  File "aqt", line 131, in open
  File "aqt.hooks_gen", line 1872, in __call__
  File "C:\Users\*****\AppData\Roaming\Anki2\addons21\308574457\__init__.py", line 234, in on_dialog_manager_did_open_dialog
    context.form.web.eval(load_custom_style_wrapper())
AttributeError: 'Ui_Dialog' object has no attribute 'web'
```

**Comment by Shirajuki** [comment]
Hello! I was on quite a rush yesterday and released an update before testing all the functionalities. A fix was quickly updated yesterday after discovering this same bug some minutes later. Anki should therefore be asking for a new update pointing to the new one instead of the old though 🤔. You can manually click on the "check for updates" button on the add-ons page on Anki to see if an update to the newly fixed version is available.

As for the buttons not having the same, uncheck the Advanced Review Bottom Bar compatibility fix if you don't have the add-on or don't want it overwritten by Anki-redesign. Also:
![image](https://user-images.githubusercontent.com/20891306/181180282-d213fe4c-17c8-424a-91ce-c6f3dc91017b.png)

**Comment by drunkzurg** [comment]
yep, it seems to work now. Thank you

**Comment by Shirajuki** [comment]
Great! Closing the issue! :)
