### ISSUE TITLE
Bug:Font change after a button is clicked will not work in night mode

### ISSUE THREAD

**Issue by Jerfain** [Shirajuki/anki-redesign#40]
<img width="1920" alt="图片" src="https://user-images.githubusercontent.com/69144012/184681374-1605a60c-a35e-48d8-beed-93f99e25f1af.png">
<img width="1920" alt="图片" src="https://user-images.githubusercontent.com/69144012/184681385-6d02d80f-f773-4a0c-b8e8-4270c91009ea.png">
<img width="1920" alt="图片" src="https://user-images.githubusercontent.com/69144012/184681393-2e12369a-0884-4435-845f-0161c92d35b2.png">
<img width="1920" alt="图片" src="https://user-images.githubusercontent.com/69144012/184681399-36ee6c3c-04f3-45dd-851c-8390f131afde.png">
In day mode, my primary color is set to black, and after I click the button, my button background changes to black and the font automatically changes from black to white, but in night mode, my primary color is set to white, and after I click the button, the font color does not automatically change from white to black, causing the font color and the button background to blend into one.

**Comment by Shirajuki** [comment]
Hello again @Jerfain!
Thank you once again for a bug report!
I have been busy these past few weeks due to work and studies, but now I am back again to work on some updates! 🥳 
This bug seems to be similar to #32 and will thus be included in the next update where I will be revamping the whole theme-engine part of the add-on. The custom themes made will after that be correct as well as persistent in their changes and saved on updates.

**Comment by Shirajuki** [comment]
Heyoheyo!
A new version of Anki-redesign was just recently pushed out, adding a fix to the color settings not being correctly set. I have tried to manually fix this by changing the styling of the files. Hopefully I did not forget any details and everything looks good now. I'll be leaving this issue open for now. 🥳

**Comment by Shirajuki** [comment]
Some time has passed and I see no updates, I hope it's fixed now? :D
Closing the issue!
Feel free to reopen a new one if I missed something!
