### ISSUE TITLE
visual issue with "advanced review buttom bar"

### ISSUE THREAD

**Issue by ahmad123ahmad** [Shirajuki/anki-redesign#51]
hello there , thank you for the add on its really great
however the issue is when I edited the add on "advanced review bottom bar" (aka ARBb) settings and also checked the box of it in the setting of the anki redesign , the cards count (new, learning, review ) in the bottoms bar (above the good , easy...bottoms) is almost gone
I tried adjusting the setting of the ARBb but it did not work 
![Untitled](https://user-images.githubusercontent.com/116543025/197462850-1807b8f2-9b3e-446f-b65d-cde67c208f78.png)

**Comment by slow-down** [comment]
Did you find a workaround while it's being fixed? Because even if I disable the ARBb Addon it still cuts off at the bottom. I would really like to use this addon

**Comment by kongzhh1101** [comment]
I have the same problem on Mac 
<img width="1280" alt="Screen Shot 2022-11-23 at 3 46 20 PM" src="https://user-images.githubusercontent.com/67037833/203495356-0c652829-3e92-47c8-b2f6-6fe137f4c00a.png">

**Comment by Shirajuki** [comment]
Hello!
Thank you very much for the issue. This is actually a recurring problem I've seen happening for many users, therefore I will be prioritizing this issue first for the next update.

I am however very busy with my studies as of now, and won't be working on the update until after christmas. Hopefully you and the others can wait until then. Thank you very much for contributing to Anki-redesign!

**Comment by slow-down** [comment]
I tried the workaround but it didn't work. it only moves it even higher up. i also tried different values/negative values but the text just seems like it is fixed and i can't seem to get it to move down, even if i make the bottom bar like 200px the text is still cut off at the top of the bottom bar

**Comment by JoshCaiLi** [comment]
I'm on Anki 2.1.54 Qt6 and it works fine. Maybe you and other users are on the newest version of Anki making the addon incompatible? https://docs.ankiweb.net/platform/windows/installing.html#qt5-vs-qt6. Or try qt5 because it says "Disadvantages of the Qt6 version: Some add-ons currently only work with the Qt5 version."

**Comment by slow-down** [comment]
I am on Anki 2.1.49 but I will try to update in the next days and try it again. But I doubt it will work because the addon page says it should work for anki 2.1.20 until 2.1.54. @JoshCaiLi are you sure you also have the ARBb installed? could you show a screenshot of how the bottom bar looks like while reviewing?

**Comment by Shirajuki** [comment]
Hello again!
I have just recently added a new update of Anki-redesign hopefully fixing this. If the problem still occurs, feel free to open a new issue. Thank you all for being a user of Anki-redesign! :)

Closing this issue!
