### ISSUE TITLE
Programming decks

### ISSUE THREAD

**Issue by mercifulboss** [Shirajuki/anki-redesign#58]
This is not related to the program - but it seems like you are doing computer science and I wanted to ask if you could post your programming anki decks as I am taking similar courses and it would help to have well made cards :)

**Comment by kvn1351** [comment]
Bruh

**Comment by Shirajuki** [comment]
Hello! I am actually very humbled to have someone ask for notes from me, specifically anki decks. 😅
Unfortunately, truth to be told, I am actually a very bad student and haven't taken any notes since my first year as an university student. For programming, I personally do not use Anki that much as I am more keen in the kinesthetic learning style, also I prefer to learn by doing rather than memorizing. This means doing project, using the learnt theory in practice and such. Instead, I mainly use Anki for learning languages such as chinese and japanese.

That said, I did try to use Anki one semester for my courses and from that began working on this add-on. (you can see the decks I created for the different courses in the images showcasing the addon) The decks are though long deleted unfortunately. It is also very sloppily made and would definitely not have been good to use anyway. I am sorry 😅
