### ISSUE TITLE
Error on startup with version 2.1.55

### ISSUE THREAD

**Issue by Munzu** [Shirajuki/anki-redesign#59]
I just upgraded my Anki to verson 2.1.55 and get the following error on startup:

```
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Anki-redesign⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 247, in loadAddons
    __import__(addon.dir_name)
  File "/home/tai/.local/share/Anki2/addons21/308574457/__init__.py", line 259, in <module>
    from .utils import dialog
  File "/home/tai/.local/share/Anki2/addons21/308574457/utils/dialog.py", line 491, in <module>
    update_theme()
  File "/home/tai/.local/share/Anki2/addons21/308574457/utils/dialog.py", line 420, in update_theme
    apply_theme(ncolors)
  File "/home/tai/.local/share/Anki2/addons21/308574457/utils/dialog.py", line 462, in apply_theme
    theme_manager._apply_palette(mw.app) # Update palette theme_manager
  File "/usr/lib/python3.10/site-packages/aqt/theme.py", line 289, in _apply_palette
    hlbg = self.qcolor(colors.HIGHLIGHT_BG)
  File "/usr/lib/python3.10/site-packages/aqt/theme.py", line 187, in qcolor
    r"rgba\((\d+),\s*(\d+),\s*(\d+),\s*(\d+\.*\d+?)\)", self.var(colors)
  File "/usr/lib/python3.10/site-packages/aqt/theme.py", line 181, in var
    return vars["dark" if self.night_mode else "light"]
TypeError: tuple indices must be integers or slices, not str
```

- Version ⁨2.1.55 (01caec2a)⁩
- Python 3.10.8 Qt 6.4.1 PyQt 6.4.0
- Arch Linux, Wayland, Gnome

**Comment by soccerwithag** [comment]
Also getting the type error "tuple indices must be integers or slices, not str" when trying to open browse window. Issue goes away when disabling anki-redesign. @Shirajuki

**Comment by Shirajuki** [comment]
Hello!
Thank you for the issue! As of now the addon doesn't work on the latest version of 2.1.55. I am currently working on a fix for that as well as some other issues. I am on a christmas break now, so hopefully I'll get to figure out a fix for this asap in the next few days/week!

**Comment by chezfo** [comment]
In fact, anki .55 tries to follow this wonderful plugin…

I'm really looking forward to the update!!

Well done!

**Comment by ganqqwerty** [comment]
hmm looks like, in the new version, the anki creators borrowed some ideas, which is great. Looking forward for updates, love the addon and its flexibility

**Comment by chezfo** [comment]
They said it explicitly.

**Comment by Shirajuki** [comment]
Hello hello again! 👋
I apologize for the slow update these past few months. Due to it being my last semester in university, I haven't had the time check out the new update at all, nor have had the motivation to maintain the add-on as much as before since I don't really use Anki anymore sadly (a little bit too busy with other things haha). I had some time when I was sitting on the train traveling back to my hometown a few days ago and actually got a fix ready, but I'll need more time to polish the add-on a little bit more. The changes were actually quite easily fixable after quickly going through the source code.

The new UI update added lots of new changes and it does look a bit similar yeah. Some update on the CSS styling on the add-on has to be done as well to fix some minor styling issues. I guess the add-on will at some point in the future be redundant with the upcoming UI focused updates, which is actually nice that they for once are progressing in terms of UX. I see that the version 2.1.57 are in the works as of now too, so I'll be trying my best to keep up with the updates while in Beta so that you guys won't be waiting that long if any break were to occur again.

Once again, thank you very much for helping with the development of Anki-redesign as well as using the add-on, I really appreciate it 🙏

**Comment by Shirajuki** [comment]
Hello again!
Just released an update adding a partially compatibility fix for 2.1.56. The addon should hopefully startup correctly without any errors now. Unluckily, I see that 2.1.57 is released as well, the future plan will be to assure compatibility with it asap when I have the time, as well as updating the themes to look more clean with the new UI changes. (currently, only the theme Anki is actually styled correctly).

Thank you all for the patience and support all along!
I'll let the issue be open for further discussions and occurring problems if any :)

**Comment by chezfo** [comment]
> I guess the add-on will at some point in the future be redundant with the upcoming UI focused updates, which is actually nice that they for once are progressing in terms of UX.

I'm really skeptical about the question of how open Anki is to moving forward in terms of UX.

When they moved to .56, some big protest in the forum because of the new design.

You are the hope of the "normal" side of humanity 😆

**Comment by Shirajuki** [comment]
> I'm really skeptical about the question of how open Anki is to moving forward in terms of UX.
> When they moved to .56, some big protest in the forum because of the new design.
> You are the hope of the "normal" side of humanity 😆

Haha, hopefully I won't let you guys down. Let's just hope for the best :)

I just recently added a new version of Anki-redesign. This adds a lot of bugfixes, and the add-on should now be compatible with Anki 2.1.57! I'll be closing this issue for now, so feel free to create new issues if there is still any bugs still occurring.

Thank you all for the patience and support all along!
