### ISSUE TITLE
[Feature] Change accent color

### ISSUE THREAD

**Issue by ebanDev** [Shirajuki/anki-redesign#9]
It could be really cool to have a "change accent color" option in the addon config (with just a simple color picker + ability to add hexadecimal color)

**Comment by Shirajuki** [comment]
Hello again! I have just added a new major update for Anki-redesign. Since commit c64c34de94cf46a63cd8c808ed73eb882a80257d, a dialog for Anki-redesign is implemented and can be accessed through a new menu on the top of the screen named "Anki-redesign".

Color picker functionality is added for not just the primary/accent color but all other default css variables as well!
I hope this update was worth the wait :D

I'll be closing this issue :)
